/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface AaveTokenInterface extends Interface {
  functions: {
    DOMAIN_SEPARATOR: TypedFunctionDescription<{ encode([]: []): string }>;

    PERMIT_TYPEHASH: TypedFunctionDescription<{ encode([]: []): string }>;

    REVISION: TypedFunctionDescription<{ encode([]: []): string }>;

    _aaveGovernance: TypedFunctionDescription<{ encode([]: []): string }>;

    _countsSnapshots: TypedFunctionDescription<{
      encode([]: [string]): string;
    }>;

    _nonces: TypedFunctionDescription<{ encode([]: [string]): string }>;

    _snapshots: TypedFunctionDescription<{
      encode([,]: [string, BigNumberish]): string;
    }>;

    allowance: TypedFunctionDescription<{
      encode([owner, spender]: [string, string]): string;
    }>;

    approve: TypedFunctionDescription<{
      encode([spender, amount]: [string, BigNumberish]): string;
    }>;

    balanceOf: TypedFunctionDescription<{
      encode([account]: [string]): string;
    }>;

    decimals: TypedFunctionDescription<{ encode([]: []): string }>;

    decreaseAllowance: TypedFunctionDescription<{
      encode([spender, subtractedValue]: [string, BigNumberish]): string;
    }>;

    increaseAllowance: TypedFunctionDescription<{
      encode([spender, addedValue]: [string, BigNumberish]): string;
    }>;

    initialize: TypedFunctionDescription<{
      encode([migrator, distributor, aaveGovernance, chainId]: [
        string,
        string,
        string,
        BigNumberish
      ]): string;
    }>;

    name: TypedFunctionDescription<{ encode([]: []): string }>;

    permit: TypedFunctionDescription<{
      encode([owner, spender, expiration, amount, v, r, s]: [
        string,
        string,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        Arrayish,
        Arrayish
      ]): string;
    }>;

    symbol: TypedFunctionDescription<{ encode([]: []): string }>;

    totalSupply: TypedFunctionDescription<{ encode([]: []): string }>;

    transfer: TypedFunctionDescription<{
      encode([recipient, amount]: [string, BigNumberish]): string;
    }>;

    transferFrom: TypedFunctionDescription<{
      encode([sender, recipient, amount]: [
        string,
        string,
        BigNumberish
      ]): string;
    }>;
  };

  events: {
    Approval: TypedEventDescription<{
      encodeTopics([owner, spender, value]: [
        string | null,
        string | null,
        null
      ]): string[];
    }>;

    SnapshotDone: TypedEventDescription<{
      encodeTopics([owner, oldValue, newValue]: [null, null, null]): string[];
    }>;

    Transfer: TypedEventDescription<{
      encodeTopics([from, to, value]: [
        string | null,
        string | null,
        null
      ]): string[];
    }>;
  };
}

export class AaveToken extends Contract {
  connect(signerOrProvider: Signer | Provider | string): AaveToken;
  attach(addressOrName: string): AaveToken;
  deployed(): Promise<AaveToken>;

  on(event: EventFilter | string, listener: Listener): AaveToken;
  once(event: EventFilter | string, listener: Listener): AaveToken;
  addListener(eventName: EventFilter | string, listener: Listener): AaveToken;
  removeAllListeners(eventName: EventFilter | string): AaveToken;
  removeListener(eventName: any, listener: Listener): AaveToken;

  interface: AaveTokenInterface;

  functions: {
    DOMAIN_SEPARATOR(): Promise<string>;

    PERMIT_TYPEHASH(): Promise<string>;

    REVISION(): Promise<BigNumber>;

    _aaveGovernance(): Promise<string>;

    _countsSnapshots(arg0: string): Promise<BigNumber>;

    _nonces(arg0: string): Promise<BigNumber>;

    _snapshots(
      arg0: string,
      arg1: BigNumberish
    ): Promise<{
      blockNumber: BigNumber;
      value: BigNumber;
      0: BigNumber;
      1: BigNumber;
    }>;

    allowance(owner: string, spender: string): Promise<BigNumber>;

    approve(
      spender: string,
      amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    balanceOf(account: string): Promise<BigNumber>;

    decimals(): Promise<number>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    initialize(
      migrator: string,
      distributor: string,
      aaveGovernance: string,
      chainId: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    name(): Promise<string>;

    permit(
      owner: string,
      spender: string,
      expiration: BigNumberish,
      amount: BigNumberish,
      v: BigNumberish,
      r: Arrayish,
      s: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    symbol(): Promise<string>;

    totalSupply(): Promise<BigNumber>;

    transfer(
      recipient: string,
      amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  DOMAIN_SEPARATOR(): Promise<string>;

  PERMIT_TYPEHASH(): Promise<string>;

  REVISION(): Promise<BigNumber>;

  _aaveGovernance(): Promise<string>;

  _countsSnapshots(arg0: string): Promise<BigNumber>;

  _nonces(arg0: string): Promise<BigNumber>;

  _snapshots(
    arg0: string,
    arg1: BigNumberish
  ): Promise<{
    blockNumber: BigNumber;
    value: BigNumber;
    0: BigNumber;
    1: BigNumber;
  }>;

  allowance(owner: string, spender: string): Promise<BigNumber>;

  approve(
    spender: string,
    amount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  balanceOf(account: string): Promise<BigNumber>;

  decimals(): Promise<number>;

  decreaseAllowance(
    spender: string,
    subtractedValue: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  increaseAllowance(
    spender: string,
    addedValue: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  initialize(
    migrator: string,
    distributor: string,
    aaveGovernance: string,
    chainId: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  name(): Promise<string>;

  permit(
    owner: string,
    spender: string,
    expiration: BigNumberish,
    amount: BigNumberish,
    v: BigNumberish,
    r: Arrayish,
    s: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  symbol(): Promise<string>;

  totalSupply(): Promise<BigNumber>;

  transfer(
    recipient: string,
    amount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  transferFrom(
    sender: string,
    recipient: string,
    amount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {
    Approval(
      owner: string | null,
      spender: string | null,
      value: null
    ): EventFilter;

    SnapshotDone(owner: null, oldValue: null, newValue: null): EventFilter;

    Transfer(from: string | null, to: string | null, value: null): EventFilter;
  };

  estimate: {
    DOMAIN_SEPARATOR(): Promise<BigNumber>;

    PERMIT_TYPEHASH(): Promise<BigNumber>;

    REVISION(): Promise<BigNumber>;

    _aaveGovernance(): Promise<BigNumber>;

    _countsSnapshots(arg0: string): Promise<BigNumber>;

    _nonces(arg0: string): Promise<BigNumber>;

    _snapshots(arg0: string, arg1: BigNumberish): Promise<BigNumber>;

    allowance(owner: string, spender: string): Promise<BigNumber>;

    approve(spender: string, amount: BigNumberish): Promise<BigNumber>;

    balanceOf(account: string): Promise<BigNumber>;

    decimals(): Promise<BigNumber>;

    decreaseAllowance(
      spender: string,
      subtractedValue: BigNumberish
    ): Promise<BigNumber>;

    increaseAllowance(
      spender: string,
      addedValue: BigNumberish
    ): Promise<BigNumber>;

    initialize(
      migrator: string,
      distributor: string,
      aaveGovernance: string,
      chainId: BigNumberish
    ): Promise<BigNumber>;

    name(): Promise<BigNumber>;

    permit(
      owner: string,
      spender: string,
      expiration: BigNumberish,
      amount: BigNumberish,
      v: BigNumberish,
      r: Arrayish,
      s: Arrayish
    ): Promise<BigNumber>;

    symbol(): Promise<BigNumber>;

    totalSupply(): Promise<BigNumber>;

    transfer(recipient: string, amount: BigNumberish): Promise<BigNumber>;

    transferFrom(
      sender: string,
      recipient: string,
      amount: BigNumberish
    ): Promise<BigNumber>;
  };
}
