/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface MockTransferHookInterface extends Interface {
  functions: {
    onTransfer: TypedFunctionDescription<{
      encode([from, to, amount]: [string, string, BigNumberish]): string;
    }>;
  };

  events: {
    MockHookEvent: TypedEventDescription<{ encodeTopics([]: []): string[] }>;
  };
}

export class MockTransferHook extends Contract {
  connect(signerOrProvider: Signer | Provider | string): MockTransferHook;
  attach(addressOrName: string): MockTransferHook;
  deployed(): Promise<MockTransferHook>;

  on(event: EventFilter | string, listener: Listener): MockTransferHook;
  once(event: EventFilter | string, listener: Listener): MockTransferHook;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): MockTransferHook;
  removeAllListeners(eventName: EventFilter | string): MockTransferHook;
  removeListener(eventName: any, listener: Listener): MockTransferHook;

  interface: MockTransferHookInterface;

  functions: {
    onTransfer(
      from: string,
      to: string,
      amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  onTransfer(
    from: string,
    to: string,
    amount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {
    MockHookEvent(): EventFilter;
  };

  estimate: {
    onTransfer(
      from: string,
      to: string,
      amount: BigNumberish
    ): Promise<BigNumber>;
  };
}
